version: '3.8'

services:
  web:
    build: mfc
    command: sh -c "python manage.py migrate
               && python3 manage.py runserver 0.0.0.0:8000"
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - .env